
// This file is automatically generated. Do not edit it directly.
import { getSupabaseClient } from '@/utils/supabase-optimized';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSupabaseClient();
