
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxnbnaznhubhqfjyllms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bmJuYXpuaHViaHFmanlsbG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzM3NDMsImV4cCI6MjA1MTIwOTc0M30.BxJB2-7bMCHZhgby4HudUTnTrvRwjECWFixDPjnmGwg";

// Initialize Supabase client with improved auth options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);

// Export a function to check if a user's email is confirmed
export const isEmailConfirmed = async (userId: string) => {
  const { data, error } = await supabase.auth.admin.getUserById(userId);
  if (error || !data.user) return false;
  return !!data.user.email_confirmed_at;
};
